# -*- coding: utf-8 -*-
"""Copy of Copy of Copy of Day 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aDUdvj6WLNVRgs-2NA0sCE-gEJA1jRXE

#**LISTS**
"""

fruits.count('apple')

fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

fruits.append("mango")

fruits

fruits.sort()

fruits

fruits.pop(1)

fruits

fruits.reverse()

fruits

fruits.insert(2,"grapes")

fruits

len(fruits)

"""#**DICTIONARY**"""

tel = {'jack': 4098, 'sape': 4139}

tel['guido'] = 4127

tel

tel['sape'] = "4128"

list(tel)

tel

tel

tel

'jack' in tel

"sape" not in tel

"""#**SETS**"""

x = set(['foo', 'bar', 'baz', 'foo', 'qux'])

x

x

list(x)

s1 = {2, 4, 6, 8,10}
s2 = {'Smith', 'McArthur', 'Wilson', 'Johansson'}

s1.union(s2)

y = x.union(s1)

y

list(y)

"""#**TUPLE**"""

tup1 = ('physics', 'chemistry', 1997, 2000);
tup2 = (1, 2, 3, 4, 5 );
tup3 = "a", "b", "c", "d";

tup1 = (50,);

tup2[1:5]

tup4 = tup1+ tup2 + tup3;

tup4

list(tup4)

"""#**STRINGS**"""

var1 = 'Hello World!'

var2 = "Python Programming"

var2[1:5]

var1[:6] + 'Python'